# Generated by Django 5.0.7 on 2024-08-31 00:42

import borrowings.models
import borrowings.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow",
                    models.DateField(
                        validators=[borrowings.validators.date_limit_take_book]
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        validators=[borrowings.validators.date_limit_take_book]
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[borrowings.validators.date_limit_return_book],
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Borrowing",
                        to="library.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Borrowing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")], max_length=7
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "Payment"), ("Fine", "Fine")], max_length=7
                    ),
                ),
                (
                    "session_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to stripe payment session",
                        max_length=500,
                        null=True,
                        validators=[borrowings.models.OptionalSchemeURLValidator],
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of stripe payment session",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "money_to_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
